#ifndef WORKPAGEAPLUGIN_GLOBAL_H
#define WORKPAGEAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WORKPAGEAPLUGIN_LIBRARY)
#  define WORKPAGEAPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define WORKPAGEAPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // WORKPAGEAPLUGIN_GLOBAL_H
