#ifndef WORKPAGEBPLUGIN_GLOBAL_H
#define WORKPAGEBPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WORKPAGEBPLUGIN_LIBRARY)
#  define WORKPAGEBPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define WORKPAGEBPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // WORKPAGEBPLUGIN_GLOBAL_H
