#ifndef WORKPAGECPLUGIN_GLOBAL_H
#define WORKPAGECPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WORKPAGECPLUGIN_LIBRARY)
#  define WORKPAGECPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define WORKPAGECPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // WORKPAGECPLUGIN_GLOBAL_H
